### ISSUE TITLE
🧹 Remove unnecessary rules

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default-jest#5]
## Overview

* Remove unnecessary rules

## Tasks

- [x] Remove core rules
- [x] Remove stylistic rules
- [x] Remove JSDoc rules
